osx_image: xcode9.4
language: objective-c

script:

    - xcodebuild -workspace RxCoordinator.xcworkspace -scheme 'RxCoordinator' | xcpretty -c
    - xcodebuild -workspace RxCoordinator-Example/RxCoordinator-Example.xcworkspace -scheme 'RxCoordinator-Example' | xcpretty -c